name: Spencer Harrison
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - "#fb70ff"
    - "#0a051d"
    - "#cef8fd"
    - "#e700b2"
    - "#1b4eae"
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
