name: Spencer
favicon: null
layout_spectrum: 0
typography_spectrum: 0.73785
title: Spencer Harrison
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8caed0'
    - '#7b98b6'
    - '#1f2933'
    - '#374655'
    - '#5c738b'
  brandStrength: 1
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
