name: Spencer
favicon: null
layout_spectrum: 0.26628
typography_spectrum: 0.97551
title: The Official Site for Spencer Harrison
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ededed'
    - '#b5b5b5'
    - '#979797'
    - '#292929'
    - '#515151'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
